-- SHIFT Dispatch v3.5.0 / Driver Time Sheet v1.7.0 — central shift, activity and pre-trip records.
-- Applied to project hqhfstosclasgwgxubip on 2026-10-07 (migrations: driver_live_status_app_grants, driver_timesheet_records).
-- Purely additive: three new tables. Does not touch dispatch_tasks, drivers, vehicles or any existing data.
--
-- DOT integrity rules
--   * driver_pretrips: app roles may INSERT and SELECT only (no UPDATE/DELETE grants or policies).
--     A guard trigger also rejects edits/deletes from every role, except the one-time link of shift_id.
--     Admin-only escape hatch for removing a test record (run in the SQL editor, never from the app):
--       begin; set local darwill.allow_pretrip_delete = 'on'; delete from public.driver_pretrips where id = <id>; commit;
--   * driver_shifts: app roles may INSERT/SELECT/UPDATE (End Shift upserts totals). No DELETE.
--     Driver, date, start time and ids are immutable; once a shift is completed/discarded it is locked
--     (an identical retry is accepted, any change is rejected).
--   * driver_activities: INSERT/SELECT/UPDATE, no DELETE; ids, driver and start time are immutable.

-- ---------- live status (step 1) ----------
grant select, insert, update on table public.driver_live_status to anon, authenticated;

-- ---------- shifts ----------
create table if not exists public.driver_shifts (
  id bigint generated by default as identity primary key,
  device_shift_id text not null unique,
  driver_id bigint not null references public.drivers(id),
  driver_name text not null,
  work_date date not null,
  vehicle text,
  trailer text,
  status text not null default 'open' check (status in ('open','completed','discarded')),
  shift_start timestamptz not null,
  shift_end timestamptz,
  started_at_device timestamptz,
  ended_at_device timestamptz,
  shift_minutes integer,
  driving_minutes integer,
  productive_minutes integer,
  waiting_minutes integer,
  lunch_minutes integer,
  nonproductive_minutes integer,
  productivity_pct numeric(5,1),
  activity_count integer,
  pretrip_device_id text,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_shifts_end_after_start check (shift_end is null or shift_end >= shift_start)
);
create index if not exists driver_shifts_work_date_idx on public.driver_shifts (work_date, driver_id);
create index if not exists driver_shifts_driver_idx on public.driver_shifts (driver_id);

-- ---------- pre-trip inspections (DOT) ----------
create table if not exists public.driver_pretrips (
  id bigint generated by default as identity primary key,
  device_pretrip_id text not null unique,
  shift_id bigint references public.driver_shifts(id),
  driver_id bigint references public.drivers(id),
  driver_name text not null,
  work_date date not null,
  vehicle text not null,
  trailer text,
  odometer text not null,
  condition text not null check (condition in ('acceptable','defects')),
  checklist jsonb not null,                 -- [{group,item,result:'ok'|'attention'}] in form order
  defects text[] not null default '{}',     -- items marked Needs Attention
  comments text,
  signature_name text not null,             -- typed driver acknowledgment
  submitted_at timestamptz not null,        -- device time the driver completed the inspection
  app_version text,
  created_at timestamptz not null default now()  -- server receipt time
);
create index if not exists driver_pretrips_work_date_idx on public.driver_pretrips (work_date, driver_id);
create index if not exists driver_pretrips_shift_idx on public.driver_pretrips (shift_id);
create index if not exists driver_pretrips_driver_idx on public.driver_pretrips (driver_id);

-- ---------- activities ----------
create table if not exists public.driver_activities (
  id bigint generated by default as identity primary key,
  device_activity_id text not null unique,
  device_shift_id text not null references public.driver_shifts(device_shift_id),
  shift_id bigint references public.driver_shifts(id),
  driver_id bigint not null references public.drivers(id),
  activity_type text not null,
  started_at timestamptz not null,
  ended_at timestamptz,
  minutes integer,
  location text,
  address text,
  notes text,
  reason text,
  detail jsonb,
  dispatch_task_id bigint,                  -- informational link to dispatch_tasks.id (no FK on purpose)
  created_at timestamptz not null default now()
);
create index if not exists driver_activities_shift_idx on public.driver_activities (shift_id);
create index if not exists driver_activities_device_shift_idx on public.driver_activities (device_shift_id);
create index if not exists driver_activities_driver_idx on public.driver_activities (driver_id, started_at);

-- ---------- guard / helper triggers ----------
create or replace function public.driver_shifts_guard() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.id is distinct from old.id
     or new.device_shift_id is distinct from old.device_shift_id
     or new.driver_id is distinct from old.driver_id
     or new.work_date is distinct from old.work_date
     or new.shift_start is distinct from old.shift_start
     or new.created_at is distinct from old.created_at then
    raise exception 'driver_shifts: driver, work date, start time and ids cannot be changed (shift %)', old.id
      using errcode = 'check_violation';
  end if;
  if old.status <> 'open'
     and (to_jsonb(new) - 'updated_at') is distinct from (to_jsonb(old) - 'updated_at') then
    raise exception 'driver_shifts: shift % is % and locked; records cannot be overwritten', old.id, old.status
      using errcode = 'check_violation';
  end if;
  if (to_jsonb(new) - 'updated_at') is distinct from (to_jsonb(old) - 'updated_at') then
    new.updated_at := now();
  else
    new.updated_at := old.updated_at;
  end if;
  return new;
end $$;
drop trigger if exists driver_shifts_guard on public.driver_shifts;
create trigger driver_shifts_guard before update on public.driver_shifts
  for each row execute function public.driver_shifts_guard();

-- Link the pre-trip to its shift (one time, shift_id null -> id). SECURITY DEFINER because app roles have no UPDATE on pre-trips.
create or replace function public.driver_shifts_link_pretrip() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.pretrip_device_id is not null then
    update public.driver_pretrips set shift_id = new.id
     where device_pretrip_id = new.pretrip_device_id and shift_id is null;
  end if;
  return null;
end $$;
revoke execute on function public.driver_shifts_link_pretrip() from public, anon, authenticated;
drop trigger if exists driver_shifts_link_pretrip on public.driver_shifts;
create trigger driver_shifts_link_pretrip after insert or update of pretrip_device_id on public.driver_shifts
  for each row execute function public.driver_shifts_link_pretrip();

create or replace function public.driver_pretrips_before_insert() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.shift_id is null then
    select s.id into new.shift_id from public.driver_shifts s where s.pretrip_device_id = new.device_pretrip_id limit 1;
  end if;
  return new;
end $$;
drop trigger if exists driver_pretrips_before_insert on public.driver_pretrips;
create trigger driver_pretrips_before_insert before insert on public.driver_pretrips
  for each row execute function public.driver_pretrips_before_insert();

create or replace function public.driver_pretrips_guard() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    if coalesce(current_setting('darwill.allow_pretrip_delete', true), '') <> 'on' then
      raise exception 'driver_pretrips: pre-trip inspection records are retained (DOT) and cannot be deleted'
        using errcode = 'insufficient_privilege';
    end if;
    return old;
  end if;
  if (to_jsonb(new) - 'shift_id') is distinct from (to_jsonb(old) - 'shift_id')
     or (old.shift_id is not null and new.shift_id is distinct from old.shift_id) then
    raise exception 'driver_pretrips: pre-trip inspection % is read-only once submitted', old.id
      using errcode = 'insufficient_privilege';
  end if;
  return new;
end $$;
drop trigger if exists driver_pretrips_guard on public.driver_pretrips;
create trigger driver_pretrips_guard before update or delete on public.driver_pretrips
  for each row execute function public.driver_pretrips_guard();

create or replace function public.driver_activities_before_write() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'UPDATE' then
    if new.id is distinct from old.id
       or new.device_activity_id is distinct from old.device_activity_id
       or new.device_shift_id is distinct from old.device_shift_id
       or new.driver_id is distinct from old.driver_id
       or new.started_at is distinct from old.started_at
       or new.created_at is distinct from old.created_at then
      raise exception 'driver_activities: ids, driver and start time cannot be changed (activity %)', old.id
        using errcode = 'check_violation';
    end if;
  end if;
  if new.shift_id is null then
    select s.id into new.shift_id from public.driver_shifts s where s.device_shift_id = new.device_shift_id;
  end if;
  if new.minutes is null and new.ended_at is not null then
    new.minutes := greatest(0, round(extract(epoch from (new.ended_at - new.started_at)) / 60))::integer;
  end if;
  return new;
end $$;
drop trigger if exists driver_activities_before_write on public.driver_activities;
create trigger driver_activities_before_write before insert or update on public.driver_activities
  for each row execute function public.driver_activities_before_write();

-- ---------- privileges ----------
revoke all on table public.driver_shifts, public.driver_activities, public.driver_pretrips from anon, authenticated;
grant select, insert, update on table public.driver_shifts, public.driver_activities to anon, authenticated;
grant select, insert on table public.driver_pretrips to anon, authenticated;

-- ---------- row level security ----------
alter table public.driver_shifts enable row level security;
alter table public.driver_activities enable row level security;
alter table public.driver_pretrips enable row level security;

drop policy if exists "driver shifts read" on public.driver_shifts;
drop policy if exists "driver shifts insert" on public.driver_shifts;
drop policy if exists "driver shifts update" on public.driver_shifts;
create policy "driver shifts read" on public.driver_shifts for select to anon, authenticated using (true);
create policy "driver shifts insert" on public.driver_shifts for insert to anon, authenticated with check (true);
create policy "driver shifts update" on public.driver_shifts for update to anon, authenticated using (true) with check (true);

drop policy if exists "driver activities read" on public.driver_activities;
drop policy if exists "driver activities insert" on public.driver_activities;
drop policy if exists "driver activities update" on public.driver_activities;
create policy "driver activities read" on public.driver_activities for select to anon, authenticated using (true);
create policy "driver activities insert" on public.driver_activities for insert to anon, authenticated with check (true);
create policy "driver activities update" on public.driver_activities for update to anon, authenticated using (true) with check (true);

drop policy if exists "driver pretrips read" on public.driver_pretrips;
drop policy if exists "driver pretrips insert" on public.driver_pretrips;
create policy "driver pretrips read" on public.driver_pretrips for select to anon, authenticated using (true);
create policy "driver pretrips insert" on public.driver_pretrips for insert to anon, authenticated with check (true);
-- intentionally no UPDATE / DELETE policies on driver_pretrips
