-- SHIFT Dispatch v2.5 — Saved Customer Locations
-- Run once in Supabase SQL Editor.

create table if not exists public.saved_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists saved_locations_name_address_idx
on public.saved_locations (lower(name), lower(address));

alter table public.saved_locations enable row level security;

drop policy if exists "saved locations public testing" on public.saved_locations;
create policy "saved locations public testing"
on public.saved_locations
for all
to public
using (true)
with check (true);
