-- SHIFT Dispatch v3.8.0 — MULTI-STOP ROUTES.
-- Applied to project hqhfstosclasgwgxubip on 2026-10-07 as migration "dispatch_task_stops_routes".
-- Additive only: one new table, two new nullable dispatch_tasks columns, one view, one trigger. No backfill;
-- existing dispatch_tasks rows are unchanged (new columns are NULL on them).
--
-- Model: a task is the route. The task's pickup (pickup_name/address) is the ORIGIN; dispatch_task_stops are the
-- stops after leaving the origin, in seq order (the last stop can be "back at McCook"). For route tasks the
-- dashboard mirrors the last stop into delivery_name/delivery_address so older screens still read sensibly.
-- A task with no stops behaves exactly as before (one-way pickup → delivery).

-- 1. dispatch_tasks: route flag + "combined into" link (both nullable; existing rows stay NULL = not a route / not combined)
alter table public.dispatch_tasks
  add column if not exists combined_into_task_id bigint references public.dispatch_tasks(id) on delete set null,
  add column if not exists is_route boolean;
-- default set AFTER the column exists, so existing rows stay NULL (NULL and false both mean "not a route")
alter table public.dispatch_tasks alter column is_route set default false;
alter table public.dispatch_tasks drop constraint if exists dispatch_tasks_not_combined_into_self;
alter table public.dispatch_tasks add constraint dispatch_tasks_not_combined_into_self
  check (combined_into_task_id is null or combined_into_task_id <> id);
create index if not exists dispatch_tasks_combined_into_idx on public.dispatch_tasks (combined_into_task_id)
  where combined_into_task_id is not null;

-- 2. stops
create table if not exists public.dispatch_task_stops (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  task_id bigint not null references public.dispatch_tasks(id) on delete cascade,
  seq integer not null default 0,                                   -- order within the route (1, 2, 3 …)
  location_id bigint references public.saved_locations(id) on delete set null,  -- NULL for built-in/typed places
  location_name text,                                               -- snapshot at the time the stop was planned
  location_address text,                                            -- snapshot
  stop_type text not null default 'delivery' check (stop_type in ('pickup','delivery','both')),
  material text,
  pallet_qty integer,
  notes text,
  status text not null default 'pending' check (status in ('pending','arrived','done')),
  gps_arrived_at timestamptz,                                       -- written by the Verizon GPS bot
  gps_departed_at timestamptz,                                      -- written by the Verizon GPS bot
  gps_vehicle_id bigint references public.vehicles(id) on delete set null,
  gps_source text default 'verizon_reveal',
  gps_updated_at timestamptz,
  gps_dwell_minutes integer generated always as
    (round(extract(epoch from (gps_departed_at - gps_arrived_at)) / 60)::integer) stored   -- never write this
);
create index if not exists dispatch_task_stops_task_seq_idx on public.dispatch_task_stops (task_id, seq);  -- not unique: lets the UI re-sequence freely
create index if not exists dispatch_task_stops_gps_vehicle_idx on public.dispatch_task_stops (gps_vehicle_id);
create index if not exists dispatch_task_stops_location_idx on public.dispatch_task_stops (location_id);

-- same access pattern as the other dispatch tables (anon key = the dashboard), minus TRUNCATE/TRIGGER/REFERENCES/MAINTAIN
alter table public.dispatch_task_stops enable row level security;
revoke all on table public.dispatch_task_stops from anon, authenticated;
grant select, insert, update, delete on table public.dispatch_task_stops to anon, authenticated;
drop policy if exists "dispatch task stops public testing" on public.dispatch_task_stops;
create policy "dispatch task stops public testing" on public.dispatch_task_stops
  for all to anon, authenticated using (true) with check (true);

-- 3. route completion: when every stop of a task is 'done', the task becomes status='completed'
--    (completed_at = last stop's gps_arrived_at, else now()). Forward-only: it never re-opens a task.
create or replace function public.dispatch_task_stops_route_complete()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare v_last timestamptz;
begin
  if new.status = 'done'
     and not exists (select 1 from public.dispatch_task_stops s where s.task_id = new.task_id and s.status <> 'done') then
    select s.gps_arrived_at into v_last from public.dispatch_task_stops s
      where s.task_id = new.task_id order by s.seq desc, s.id desc limit 1;
    update public.dispatch_tasks t
       set status = 'completed', completed_at = coalesce(t.completed_at, v_last, now())
     where t.id = new.task_id and t.status is distinct from 'completed';
  end if;
  return null;
end $$;
drop trigger if exists dispatch_task_stops_route_complete on public.dispatch_task_stops;
create trigger dispatch_task_stops_route_complete
  after insert or update of status on public.dispatch_task_stops
  for each row execute function public.dispatch_task_stops_route_complete();

-- 4. per-stop view with leg drive minutes (previous stop's departure → this stop's arrival;
--    leg 1 uses the task's origin departure dispatch_tasks.gps_departed_at), driver and planned truck.
create or replace view public.dispatch_route_stops_v with (security_invoker = true) as
select
  s.id as stop_id, s.task_id, s.seq,
  row_number() over w as stop_number,
  count(*) over (partition by s.task_id) as stop_count,
  s.stop_type, s.location_id, s.location_name, s.location_address, s.material, s.pallet_qty, s.notes, s.status,
  case when lag(s.id) over w is null then t.pickup_name else lag(s.location_name) over w end as prev_location_name,
  case when lag(s.id) over w is null then t.gps_departed_at else lag(s.gps_departed_at) over w end as prev_departed_at,
  s.gps_arrived_at, s.gps_departed_at,
  round(extract(epoch from (s.gps_arrived_at -
    case when lag(s.id) over w is null then t.gps_departed_at else lag(s.gps_departed_at) over w end)) / 60)::integer
    as leg_drive_minutes,
  s.gps_dwell_minutes,
  s.gps_vehicle_id, sv.name as gps_vehicle_name, s.gps_source, s.gps_updated_at,
  t.work_date, t.title as task_title, t.task_type, t.status as task_status, t.is_route, t.combined_into_task_id,
  t.scheduled_at, t.planning_stage, t.sort_order, t.completed_at as task_completed_at,
  t.pickup_name as origin_name, t.pickup_address as origin_address, t.gps_departed_at as origin_departed_at,
  t.assigned_driver_id as driver_id, d.name as driver_name,
  coalesce(ds.vehicle_id, d.default_vehicle_id) as vehicle_id, v.name as vehicle_name   -- planned truck (Driver Schedule)
from public.dispatch_task_stops s
join public.dispatch_tasks t on t.id = s.task_id
left join public.drivers d on d.id = t.assigned_driver_id
left join public.driver_schedule ds on ds.driver_id = t.assigned_driver_id and ds.work_date = t.work_date
left join public.vehicles v on v.id = coalesce(ds.vehicle_id, d.default_vehicle_id)
left join public.vehicles sv on sv.id = s.gps_vehicle_id
window w as (partition by s.task_id order by s.seq, s.id);
revoke all on public.dispatch_route_stops_v from anon, authenticated;
grant select on public.dispatch_route_stops_v to anon, authenticated;
