-- SHIFT Dispatch v3.4.0 — OPTIONAL. The driver app works WITHOUT running this.
-- Run once in Supabase SQL Editor if you want an audit trail of assign / start / done / missed / refused events.
-- Purely additive: creates one new table. Does not touch dispatch_tasks or any existing data.

create table if not exists public.dispatch_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  task_id bigint,
  driver_id bigint,
  event text not null,          -- created | assigned | started | completed | undo_completed | missed | refused
  detail jsonb
);
create index if not exists dispatch_events_task_idx on public.dispatch_events (task_id, created_at desc);

alter table public.dispatch_events enable row level security;
drop policy if exists "dispatch events public testing" on public.dispatch_events;
create policy "dispatch events public testing" on public.dispatch_events
for all to public using (true) with check (true);
